---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mineur-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mineur-docker
  template:
    metadata:
      labels:
        app: mineur-docker
    spec:
      containers:
      - name: mineur-docker
        image: 090380/mineur-docker:1.00
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: mineur-docker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31011
  selector:
    app: mineur-docker

